spring.application.name=employee

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_erp
spring.datasource.username=postgres
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=jwt.secret=QJHpGzT@#u2GJk^vR8lA3!xMZcN9sTfX

jwt.expiration=86400000

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=irizajoella2006@gmail.com
spring.mail.password=gceq bcqb yjoh jtgk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server Configuration
server.port=8081

# SQL Initialization
spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:db/schema.sql,classpath:db/triggers.sql
spring.jpa.defer-datasource-initialization=true
